### ISSUE TITLE
Allow own referrals for specific affiliate accounts

### ISSUE THREAD

**Issue by gspice** [awesomemotive/affiliatewp-allow-own-referrals#4]
Good suggestion from this HS ticket:
https://secure.helpscout.net/conversation/601889760/84239?folderId=1170842

> The question is if I activate this add on, does it apply globally to all affiliates? Can I specifically select the affiliates that would benefit from this feature? I only want a few selected affiliates to benefit from it.

I think it should default to be enabled for all affiliate accounts (for backwards compatibility), and then if unchecked, it can be enabled on individual affiliate accounts if desired.

**Comment by gspice** [comment]
Another request to enable on a per-affiliate basis:
https://secure.helpscout.net/conversation/657898770/89554?folderId=205524

**Comment by gspice** [comment]
Another request for this on a pre-sales HS ticket:
https://secure.helpscout.net/conversation/887085926/123786/?folderId=205529

>For example I have 100 affiliates registered out of which I want to block 50 affiliates to not use the feature of this plugin wherein they cannot earn using their own referral link, but the other 50 I want to allow them to earn using their own affiliate link.

**Comment by gspice** [comment]
HS ticket: https://secure.helpscout.net/conversation/983331660/134562/


> request ..... for the AffiliateWP - Allow Own Referrals plugin. Is there a way to have a checkbox or a toggle to allow this feature for only certain affiliates? Instead of allowing for all affiliates?

**Comment by alexstandiford** [comment]
@DrewAPicture As of this writing, this plugin is nothing more than a couple of filters that manipulate referral logic to do what this plugin needs. Before we implement this issue, I think we should implement our boilerplate.

It would probably be best to create a separate issue to set up the boilerplate, and then add that to the blitz. Do you agree?

**Comment by DrewAPicture** [comment]
> It would probably be best to create a separate issue to set up the boilerplate, and then add that to the blitz. Do you agree?
@alexstandiford Sure, let's do it.

**Comment by alexstandiford** [comment]
This can be worked on as soon as #10 is merged.

**Comment by gspice** [comment]
Added to feature request site:
https://team.affiliatewp.com/feature-requests/allow-own-referrals-for-specific-affiliate-accounts/
